openapi: 3.1.0
info:
  title: VTT Translator API
  version: 1.0.0
servers:
  - url: https://YOUR_DEPLOYED_DOMAIN  # e.g., https://vtt-translator.onrender.com
paths:
  /translate-vtt:
    post:
      summary: Translate a WebVTT file into 12 corporate languages
      description: |
        Upload a .vtt file and receive a ZIP with 12 translated .vtt files.
        Languages default to: sv-SE nb-NO da-DK de-DE fr-FR it-IT es-ES nl-NL zh-Hans zh-Hant ja-JP ko-KR.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Source .vtt file
                wrap:
                  type: integer
                  description: Line wrap length (default 42, 0 disables)
                model:
                  type: string
                  description: OpenAI model (default gpt-4o-mini)
                langs:
                  type: string
                  description: Optional space-separated language codes to override defaults
      responses:
        '200':
          description: ZIP of translated VTT files
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '400':
          description: Bad request
        '401':
          description: Missing bearer token
        '403':
          description: Invalid token
        '500':
          description: Server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
